name: Deploy VuePress Blog
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        env:
          token: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages
          folder: docs/.vuepress/dist
          build_script: npm install && npm run docs:build
